services:
  - type: web
    name: caaspirebd
    runtime: node
    plan: standard
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node render-start.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/public/health
